export default theme => ({
  content: {
    display: 'flex',
    flexFlow: 'row nowrap',
    flexGrow: 1,
    flexShrink: 0,
    padding: 8,
  },
  clickable: {
    cursor: 'pointer',
  },
  checkcircle: {
    color: '#D81B60',
    marginRight: 8,
  },
  avatar: {
    width: 24,
    height: 24,
    marginRight: 12,
    borderRadius: 18,
    overflow: 'hidden',
    background: 'white',
    minWidth: 24,
  },
  messageBubble: {
    borderRadius: 4,
    minWidth: 100,
    maxWidth: 440,
    marginLeft: 0,
    position: 'relative',
    overflowX: 'hidden',
    display: 'flex',
    flexFlow: 'column nowrap',
    flexGrow: 1,
    flexShrink: 1,
    background: 'white',
    fontFamily: 'Open Sans',
  },
  agentMessageBubble: {
    background: 'rgb(5, 125, 158)',
    color: 'white',
  },
  header: {
    paddingLeft: 12,
    paddingRight: 12,
    paddingTop: 5,
    justifyContent: 'space-between',
    display: 'flex',
    flexFlow: 'row nowrap',
    flexGrow: 1,
    flexShrink: 1,
    alignItems: 'baseline',
  },
  username: {
    fontSize: 10,
    fontWeight: 'bold',
    marginRight: 8,
    flex: '0 1 auto',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  timestamp: {
    fontSize: 10,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
    flex: '0 0 auto',
  },
  body: {
    fontSize: 12,
    lineHeight: 1.54,
    paddingLeft: 12,
    paddingRight: 12,
    paddingBottom: 8,
    marginTop: 3,
    overflowWrap: 'break-word',
  },
});